/**
 * /api/applications/[id]/feedback
 * 
 * Records outcome feedback on applications - drives learning loop:
 * - Got interview → what worked (cover letter tone, skills mentioned)
 * - Got rejected → what didn't match (missing skills, wrong seniority)
 * - No response → job may have been wrong fit
 * 
 * Over time, this adjusts:
 * - Score thresholds per company/ATS type
 * - Cover letter tone preferences
 * - Which role families are getting traction
 * - Which answer styles get callbacks
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { getCurrentUserFromRequest } from '@/lib/session';

type FeedbackOutcome = 'interview' | 'rejected' | 'no_response' | 'offer' | 'withdrawn';

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: applicationId } = await params;
  const user = await getCurrentUserFromRequest(request);
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const body = await request.json();
  const { outcome, stage, notes, gotInterview, rejectionReason, responseTimeHours } = body;

  const application = await prisma.application.findFirst({
    where: { id: applicationId, userId: user.id },
    include: {
      job: { include: { jobScores: { where: { userId: user.id } } } },
      answers: true,
    },
  });
  if (!application) return NextResponse.json({ error: 'Not found' }, { status: 404 });

  // Map outcome to status
  const statusMap: Record<FeedbackOutcome, string> = {
    interview: 'phone_screen',
    rejected: 'rejected',
    no_response: 'archived',
    offer: 'offer',
    withdrawn: 'withdrawn',
  };

  // Update application status
  await prisma.application.update({
    where: { id: applicationId },
    data: {
      status: statusMap[outcome as FeedbackOutcome] || outcome,
      notes: notes ? `${application.notes || ''}\n[${new Date().toLocaleDateString()}] ${notes}`.trim() : undefined,
    },
  });

  // Log the event
  await prisma.applicationEvent.create({
    data: {
      applicationId,
      eventType: 'status_change',
      toStatus: statusMap[outcome as FeedbackOutcome] || outcome,
      note: notes || undefined,
      metadata: {
        outcome,
        stage,
        gotInterview,
        rejectionReason,
        responseTimeHours,
        jobScore: application.job?.jobScores?.[0]?.overallScore,
        atsType: application.job?.atsType,
      },
    },
  });

  // ── Learning loop: update scoring based on outcomes ──────────────────────
  if (outcome === 'interview' || outcome === 'offer') {
    // Positive signal: this job type/company is a good match
    // Update the job score to mark it as a successful match
    if (application.jobId) {
      await prisma.jobScore.updateMany({
        where: { jobId: application.jobId, userId: user.id },
        data: { reasoning: `[INTERVIEW SIGNAL] ${application.job?.jobScores?.[0]?.reasoning || ''}` },
      });
    }

    // If cover letter worked, update writing preferences with tone that got traction
    if (gotInterview) {
      // Get the cover letter used
      const appDocs = await prisma.applicationDocument.findMany({
        where: { applicationId },
        include: { coverLetter: true },
      });
      if (appDocs.length > 0) {
        const cl = appDocs[0]?.coverLetter;
        if (cl?.tone) {
          // Reinforce this tone in writing preferences
          const prefs = await prisma.writingPreferences.findUnique({ where: { userId: user.id } });
          if (prefs) {
            const successTones = [...new Set([...(prefs.toneWords || []), cl.tone])];
            await prisma.writingPreferences.update({
              where: { userId: user.id },
              data: { toneWords: successTones.slice(0, 10) },
            });
          }
        }
      }
    }
  } else if (outcome === 'rejected' && rejectionReason) {
    // Negative signal: store rejection patterns
    // Could be: overqualified, underqualified, missing skill, salary mismatch
    await prisma.reusableAnswer.upsert({
      where: { userId_questionKey: { userId: user.id, questionKey: `_rejection_${application.company?.toLowerCase().replace(/\s+/g, '_')}` } },
      create: {
        userId: user.id,
        questionKey: `_rejection_${application.company?.toLowerCase().replace(/\s+/g, '_')}`,
        questionFamily: 'learning',
        answer: rejectionReason,
        isVerified: false,
        isAutoGenerated: true,
      },
      update: { answer: rejectionReason },
    }).catch(() => {});
  }

  // ── Return updated stats ───────────────────────────────────────────────────
  const stats = await prisma.applicationEvent.groupBy({
    by: ['eventType'],
    where: {
      application: { userId: user.id },
    },
    _count: true,
  });

  const interviewRate = await prisma.application.count({
    where: { userId: user.id, status: { in: ['phone_screen', 'interview', 'offer'] } },
  });
  const totalApps = await prisma.application.count({ where: { userId: user.id } });

  return NextResponse.json({
    success: true,
    application: { status: statusMap[outcome as FeedbackOutcome] || outcome },
    insights: {
      totalApplications: totalApps,
      interviews: interviewRate,
      interviewRate: totalApps > 0 ? Math.round((interviewRate / totalApps) * 100) : 0,
    },
  });
}
