/**
 * lib/deep-research.ts
 *
 * Generate a structured 6-axis research prompt for a company/role.
 * Returns a formatted markdown string ready to paste into Perplexity/ChatGPT.
 */

import { prisma } from '@/lib/db';

export async function generateDeepResearch(jobId: string, userId: string): Promise<string> {
  const job = await prisma.job.findUnique({ where: { id: jobId } });
  if (!job) throw new Error(`Job ${jobId} not found`);

  const [profile, workHistory, skills] = await Promise.all([
    prisma.userProfile.findUnique({ where: { userId } }),
    prisma.workHistory.findMany({ where: { userId }, orderBy: { startDate: 'desc' }, take: 3 }),
    prisma.skill.findMany({ where: { userId }, take: 8 }),
  ]);

  const candidateAngle = [
    profile?.jobTitle ? "My background: ${profile.jobTitle}" : null,
    workHistory[0] ? `Most recent role: ${workHistory[0].title} at ${workHistory[0].company}` : null,
    skills.length > 0 ? `Core skills: ${skills.map((s: any) => s.name).join(', ')}` : null,
    profile?.careerGoals ? "Goals: ${(profile.careerGoals ?? '').slice(0, 200)}" : null,
  ].filter(Boolean).join('\n');

  return `## Deep Research: ${job.company} — ${job.title}

*Paste this into Perplexity, Claude, or ChatGPT for a comprehensive company brief before your interview.*

---

### Context
I'm evaluating a ${job.title} role at ${job.company}${job.location ? ` (${job.location})` : ''}. I need actionable intelligence for my application and interview.

---

### 1. 🤖 AI & Tech Strategy
- What AI/ML products or features does ${job.company} have or are building?
- What's their known tech stack? (languages, frameworks, infrastructure)
- Do they have an engineering blog or published technical content? Key themes?
- Any notable research papers, conference talks, or open source contributions?

### 2. 📰 Recent Moves (last 6 months)
- Notable hires, especially in engineering or product leadership
- Acquisitions, partnerships, or major integrations
- Product launches, pivots, or major announcements
- Funding rounds, valuation changes, or ownership changes
- Any layoffs or hiring freezes?

### 3. 🏗️ Engineering Culture
- How do they ship? (deploy frequency, CI/CD signals)
- Remote-first, hybrid, or office-first culture?
- What do Glassdoor and Blind say about engineering culture?
- Any signals about technical debt, reorgs, or infra migrations?

### 4. 🔥 Likely Challenges
- What scaling or reliability challenges are they probably facing?
- Any signals about latency, cost, or performance pain points?
- Are they migrating platforms, models, or infra?
- What pain points come up in employee reviews?

### 5. ⚔️ Competitive Landscape
- Who are ${job.company}'s main competitors?
- What is their differentiated position or moat?
- Recent wins or losses vs competition?
- Market positioning shifts?

### 6. 🎯 My Candidate Angle
${candidateAngle}

Based on the above profile:
- What unique value do I bring to the ${job.title} role at ${job.company}?
- Which of my projects or achievements are most relevant to their current challenges?
- What narrative should I lead with in the interview?
- What gaps should I proactively address?

---
*Generated by Careeva · ${new Date().toLocaleDateString()}*`;
}
